[project]
name = "lnmarkets-trading-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ln-markets>=2.0.10",
    "numpy>=2.3.1",
    "pytelegrambotapi>=4.28.0",
    "python-dotenv>=1.1.1",
]
