name: Linting Code
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Copy files from repository
        uses: actions/checkout@v4

      - name: Update system package manager
        run: sudo apt update

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --only-dev

      - name: Lint code
        run: uv run task lint
